### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [weldr/bdcs-api-rs#64]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by bcl** [comment]
The reason we are using it is because Rocket uses toml with it, once they switch to using toml with serde we can drop it.

**Comment by dtolnay** [comment]
Oh from what I can tell they use TOML without rustc-serialize. I checked with `cargo tree` and the only place rustc-serialize shows up in your dependency graph is your direct dependency. Could you point out the places in Rocket or in bdcs-api-rs where it is necessary?

**Comment by bcl** [comment]
Ends up those were just leftovers that hadn't been removed when we moved to using serde. #65 should solve it. Thanks!
