### ISSUE TITLE
centos7 metadata database used for travis testing needs to be updated

### ISSUE THREAD

**Issue by bcl** [weldr/bdcs-api-rs#68]

**Comment by atodorov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Publish CentOS metadata.db online](https://trello.com/c/TEhwOALm/294-publish-centos-metadata-db-online)

**Comment by atodorov** [comment]
I've updated the S3 bucket with the latest metadata from Jenkins. Need to automate this (see Trello).
