### ISSUE TITLE
depclose tests are broken

### ISSUE THREAD

**Issue by atodorov** [weldr/bdcs-api-rs#75]
ATM depclose seems to produce empty output which breaks the tests. This is happening after the merge of #74 but I haven't investigated which commit exactly.

@clumens @bcl since you both worked on the offending code can you investigate what's going on and let me know if we need to update the tests ?

**Comment by clumens** [comment]
If this is the depclose-travis target, the metadata_centos7.db needs to be regenerated with the latest importer, so as to have the proper database layout.  Everything run as part of "make test" is passing for me locally.

**Comment by atodorov** [comment]
Updated metadata.db used for testing, see https://travis-ci.org/weldr/bdcs-api-rs/jobs/249305106
The current failure is an old one, due to a bug:
```
FAIL: test_depclose_3_kubernetes_toml (__main__.DepcloseTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/opt/python/2.7.13/lib/python2.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func

    return func(*(a + p.args), **p.kwargs)

  File "./test_runner.py", line 53, in test_depclose

    self.assertEqual('', err.output)

AssertionError: '' != 'error: Unable to satisfy requirement policycoreutils >= 2.5-11\n'
```
